export const metadata = {
    title: "Todo - Edit Profile",
    description: "Generated by create next app",
  };
  
  export default function EditProfileLayout({ children }) {
    return (
      <>
          {children}
      </>
    );
  }
  