export const metadata = {
  title: "Todo - Login",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <>
        {children}
    </>
  );
}
