export const metadata = {
  title: "Todo - Signup",
  description: "Generated by create next app",
};

export default function SignupLayout({ children }) {
  return (
    <>
        {children}
    </>
  );
}
