export const metadata = {
  title: "Todo - Add New Task",
  description: "Generated by create next app",
};

export default function AddTaskLayout({ children }) {
  return (
    <>
        {children}
    </>
  );
}
